version: '3'
services:
  frontend:
    image: frontend:latest
    environment:
      PORT: 5000
      REACT_APP_BACKEND_URL: localhost:8080
      PROXY_API: http://localhost:8080/
    ports:
      - 5000:5000
  backend:
    image:  backend:latest
    environment:
      PORT: 8080
      REQUEST_ORIGIN: localhost:5000
      PROXY_API: http://localhost:5000/
    ports:
      - 8080:8080