version: '3.5' 

services: 

    simple-web-service: 
      image: devopsdockeruh/simple-web-service 
      build: . 
      volumes: 
        - ./logs.txt:/mydir/logs.txt
      container_name: simple-web-service